<?php

namespace AppBundle\Repository;

/**
 * AbonoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbonoRepository extends \Doctrine\ORM\EntityRepository
{

	public function verTodos()
	{
		$dql = "SELECT a FROM AppBundle:Abono a";
		$query = $this->getEntityManager()->createQuery($dql);
		return $query->getResult();
	}
}
