<?php

namespace AppBundle\Repository;

/**
 * CuentaBancariaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CuentaBancariaRepository extends \Doctrine\ORM\EntityRepository
{
	public function getCuentas($ids)
	{
		$dql = "SELECT c FROM AppBundle:CuentaBancaria c WHERE c.numCuenta IN(:ids)";
		$query = $this->getEntityManager()->createQuery($dql);
		$query->setParameter("ids", $ids);
		return $query->getResult();
	}
}
