<?php

namespace AppBundle\Repository;

/**
 * CuentaBancariaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CuentaBancariaRepository extends \Doctrine\ORM\EntityRepository
{
	public function getCuenta($num)
	{
		$dql = "SELECT c FROM AppBundle:CuentaBancaria c WHERE c.numCuenta=?1";
		$query = $this->getEntityManager()->createQuery($dql);
		$query->setParameter(1,$num);
		return $query->getResult();
	}

	public function verTodos()
	{
		$dql = "SELECT c FROM AppBundle:CuentaBancaria c";
		$query = $this->getEntityManager()->createQuery($dql);
		return $query->getResult();
	}
}
