<?php

namespace AppBundle\Repository;

/**
 * PresupuestoAnualRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PresupuestoAnualRepository extends \Doctrine\ORM\EntityRepository
{
	
}
