<?php

namespace AppBundle\Repository;

/**
 * RecUsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecUsuarioRepository extends \Doctrine\ORM\EntityRepository
{
}
