<?php

namespace AppBundle\Repository;

/**
 * RolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RolRepository extends \Doctrine\ORM\EntityRepository
{
	public function verTodosRol(){
		$dql = "SELECT r from AppBundle:Rol r";
		$query = $this->getEntityManager()->createQuery($dql);
		return $query->getResult();
	}
}
