<?php

namespace AppBundle\Repository;

/**
 * RolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RolRepository extends \Doctrine\ORM\EntityRepository
{
	public function verTodosRol(){
		$dql = "SELECT r from AppBundle:Rol r";
		$query = $this->getEntityManager()->createQuery($dql);
		return $query->getResult();
	}

	public function getRoles($ids)
	{
		$dql = "SELECT c FROM AppBundle:Rol c WHERE c.idRol IN(:ids)";
		$query = $this->getEntityManager()->createQuery($dql);
		$query->setParameter("ids", $ids);
		return $query->getResult();
	}
}
