<?php

namespace AppBundle\Repository;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends \Doctrine\ORM\EntityRepository
{
	public function verTodosUsuarios(){
		$dql = "SELECT p from AppBundle:Usuario p";
		$query = $this->getEntityManager()->createQuery($dql);
		return $query->getResult();
	}

	public function usuarioId($email){
		$dql = "SELECT p.password from AppBundle:Usuario p WHERE p.email=?1";
		$query = $this->getEntityManager()->createQuery($dql);
		$query -> setParameter(1,$email);
		return $query->getResult();
	}

}
